#define SUPPORTED_VIDEO_MODE(pid, supported_video_modes, num) do {\
        if (pid == EYS3D_API_CAMERA_PID_SANDRA) { \
            supported_video_modes = &video_modes_v1[0]; \
            *num = sizeof(video_modes_v1) / sizeof(struct eys3d_video_mode); \
        } else if (pid == EYS3D_API_CAMERA_PID_NORA) { \
            supported_video_modes = &video_modes_v2[0]; \
            *num = sizeof(video_modes_v2) / sizeof(struct eys3d_video_mode); \
        } else if (pid == EYS3D_API_CAMERA_PID_EX8036) { \
            supported_video_modes = &video_modes_v3[0]; \
            *num = sizeof(video_modes_v3) / sizeof(struct eys3d_video_mode); \
        }  else if (pid == EYS3D_API_CAMERA_PID_HELEN) { \
            supported_video_modes = &video_modes_v4[0]; \
            *num = sizeof(video_modes_v4) / sizeof(struct eys3d_video_mode); \
        } else if (pid == EYS3D_API_CAMERA_PID_GRAPE) { \
            supported_video_modes = &video_modes_v5[0]; \
            *num = sizeof(video_modes_v5) / sizeof(struct eys3d_video_mode); \
        } else { \
            \
        }\
} while(0)

static const struct eys3d_video_mode video_modes_v1[] = {
    //mode #0
    {
        .mode_index = 0,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #1
    {
        .mode_index = 1,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #2
    {
        .mode_index = 2,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = true
    },
    //mode #3
    {
        .mode_index = 3,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #4
    {
        .mode_index = 4,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #5
    {
        .mode_index = 5,
        .width = 2560,
        .height = 720,
        .fps = 12,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #6
    {
        .mode_index = 6,
        .width = 2560,
        .height = 720,
        .fps = 12,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = false
    },
    //mode #7
    {
        .mode_index = 7,
        .width = 1280,
        .height = 360,
        .fps = 24,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {12, 24, 30, 60},
        .support_fps_num = 4,
        .is_scale_down = true
    }
};

//NOTE:The video modes is for NORA-FAN21-B01-000-BETA04-SLAVE and later.
static const struct eys3d_video_mode video_modes_v2[] = {
    //VM1/11 bits
    {
        .mode_index = 0,
        .width = 2048,
        .height = 768,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM1/14 bits
    {
        .mode_index = 1,
        .width = 2048,
        .height = 768,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM2/11 bits
    {
        .mode_index = 2,
        .width = 2048,
        .height = 768,
        .fps = 15,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM2/14 bits
    {
        .mode_index = 3,
        .width = 2048,
        .height = 768,
        .fps = 15,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM3/11 bits
    {
        .mode_index = 4,
        .width = 2048,
        .height = 768,
        .fps = 10,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM3/14 bits
    {
        .mode_index = 5,
        .width = 2048,
        .height = 768,
        .fps = 10,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM4/11 bits
    {
        .mode_index = 6,
        .width = 2048,
        .height = 768,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM4/14 bits
    {
        .mode_index = 7,
        .width = 2048,
        .height = 768,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM5/11 bits
    {
        .mode_index = 8,
        .width = 2048,
        .height = 768,
        .fps = 20,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM5/14 bits
    {
        .mode_index = 9,
        .width = 2048,
        .height = 768,
        .fps = 20,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM12/11 bits
    {
        .mode_index = 10,
        .width = 1024,
        .height = 384,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM12/14 bits
    {
        .mode_index = 11,
        .width = 1024,
        .height = 384,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM13/11 bits
    {
        .mode_index = 12,
        .width = 1024,
        .height = 384,
        .fps = 15,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM13/14 bits
    {
        .mode_index = 13,
        .width = 1024,
        .height = 384,
        .fps = 15,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM14/11 bits
    {
        .mode_index = 14,
        .width = 1024,
        .height = 384,
        .fps = 10,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM14/14 bits
    {
        .mode_index = 15,
        .width = 1024,
        .height = 384,
        .fps = 10,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM15/11 bits
    {
        .mode_index = 16,
        .width = 1024,
        .height = 384,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM15/14 bits
    {
        .mode_index = 17,
        .width = 1024,
        .height = 384,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM16/11 bits
    {
        .mode_index = 18,
        .width = 1024,
        .height = 384,
        .fps = 20,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM16/14 bits
    {
        .mode_index = 19,
        .width = 1024,
        .height = 384,
        .fps = 20,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM6
    {
        .mode_index = 20,
        .width = 1024,
        .height = 768,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM7
    {
        .mode_index = 21,
        .width = 1024,
        .height = 768,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM8
    {
        .mode_index = 22,
        .width = 1024,
        .height = 768,
        .fps = 10,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },

    //VM9/11 bits
    {
        .mode_index = 23,
        .width = 1024,
        .height = 768,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM9/14 bits
    {
        .mode_index = 24,
        .width = 1024,
        .height = 768,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM10/11bits
    {
        .mode_index = 25,
        .width = 1024,
        .height = 768,
        .fps = 15,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM10/14bits
    {
        .mode_index = 26,
        .width = 1024,
        .height = 768,
        .fps = 15,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM11/11bits
    {
        .mode_index = 27,
        .width = 1024,
        .height = 768,
        .fps = 10,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM11/14bits
    {
        .mode_index = 28,
        .width = 1024,
        .height = 768,
        .fps = 10,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM17
    {
        .mode_index = 29,
        .width = 512,
        .height = 384,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM18
    {
        .mode_index = 30,
        .width = 512,
        .height = 384,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM19
    {
        .mode_index = 31,
        .width = 512,
        .height = 384,
        .fps = 10,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM20/11bits
    {
        .mode_index = 32,
        .width = 512,
        .height = 384,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM20/14bits
    {
        .mode_index = 33,
        .width = 512,
        .height = 384,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM21/11bits
    {
        .mode_index = 34,
        .width = 512,
        .height = 384,
        .fps = 15,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM21/14bits
    {
        .mode_index = 35,
        .width = 512,
        .height = 384,
        .fps = 15,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM22/11bits
    {
        .mode_index = 36,
        .width = 512,
        .height = 384,
        .fps = 10,
        .depth_bits = 11,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x05,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM22/14bits
    {
        .mode_index = 37,
        .width = 512,
        .height = 384,
        .fps = 10,
        .depth_bits = 14,
        .color_bits = 0,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x03,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = true
    },
    //VM23
    {
        .mode_index = 38,
        .width = 2048,
        .height = 768,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    //VM24
    {
        .mode_index = 39,
        .width = 2048,
        .height = 768,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 10,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_SBGGR10_1X10,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x0F,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {10, 15, 30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
};

static const struct eys3d_video_mode video_modes_v3[] = {
    {
        .mode_index = 0,
        .width = 1280,
        .height = 720,
        .fps = 60,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    {
        .mode_index = 1,
        .width = 1280,
        .height = 720,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {30},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    {
        .mode_index = 2,
        .width = 1280,
        .height = 720,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x03,
        },
        .support_fps = {15},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    {
        .mode_index = 3,
        .width = 1280,
        .height = 720,
        .fps = 10,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x04,
        },
        .support_fps = {10},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    {
        .mode_index = 4,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {30},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 5,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {30},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 6,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {30},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 7,
        .width = 2560,
        .height = 720,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x03,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {30},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 8,
        .width = 1280,
        .height = 480,
        .fps = 15,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x04,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {15},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 9,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 10,
        .width = 1280,
        .height = 360,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {30},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 11,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 12,
        .width = 1280,
        .height = 360,
        .fps = 30,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x06,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {30},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 13,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 14,
        .width = 1280,
        .height = 360,
        .fps = 30,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x0E,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {30},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 15,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 16,
        .width = 1280,
        .height = 360,
        .fps = 30,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x0C,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {30},
        .support_fps_num = 1,
        .is_scale_down = false
    },
    {
        .mode_index = 17,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 11,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x1E,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = true
    },
    {
        .mode_index = 18,
        .width = 1280,
        .height = 360,
        .fps = 60,
        .depth_bits = 14,
        .color_bits = 16,
        .is_rectify = true,
        .is_interleave_mode = true,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x05,
            .cmdOpt_04 = 0x1C,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60},
        .support_fps_num = 1,
        .is_scale_down = false
    },
};

//About MEDIA_BUS_FMT_SBGGR10_1X10, please check: https://www.linuxtv.org/downloads/v4l-dvb-apis-old/pixfmt-srggb10.html
static const struct eys3d_video_mode video_modes_v4[] = {
    {
        .mode_index = 0,
        .width = 800,
        .height = 800,
        .fps = 60,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60, 50},
        .support_fps_num = 3,
        .is_scale_down = false
    },
    {
        .mode_index = 1,
        .width = 800,
        .height = 800,
        .fps = 50,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x02,
        },
        .support_fps = {60, 50},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 2,
        .width = 1600,
        .height = 800,
        .fps = 50,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60, 50},
        .support_fps_num = 2,
        .is_scale_down = false
    },
    {
        .mode_index = 3,
        .width = 1600,
        .height = 800,
        .fps = 50,
        .depth_bits = 0,
        .color_bits = 10,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_SBGGR10_1X10,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x02,
            .cmdOpt_04 = 0x02,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {60, 50},
        .support_fps_num = 2,
        .is_scale_down = false
    },
};

static const struct eys3d_video_mode video_modes_v5[] = {
    {
        .mode_index = 0,
        .width = 640,
        .height = 480,
        .fps = 15,
        .depth_bits = 0,
        .color_bits = 16,
        .is_rectify = false,
        .is_interleave_mode = false,
        .pixelcode = MEDIA_BUS_FMT_YUYV8_1X16,
        .param = {
            .cmdOpt_02 = 0x01,
            .cmdOpt_03 = 0x01,
            .cmdOpt_04 = 0x01,
            .cmdOpt_05 = 0x01,
        },
        .support_fps = {15},
        .support_fps_num = 1,
        .is_scale_down = false
    },
};