# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_HANTRO_DECODER) += hantro_vc8000d.o
obj-$(CONFIG_VIDEO_HANTRO_ENCODER) += hantro_vc8000e.o
obj-$(CONFIG_VIDEO_HANTRO_DECODER_MEM) += memalloc_d.o
obj-$(CONFIG_VIDEO_HANTRO_ENCODER_MEM) += memalloc_e.o

