# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_HANTRO_DECODER) += hx170dec.o
obj-$(CONFIG_VIDEO_HANTRO_ENCODER) += hx280enc.o
obj-$(CONFIG_VIDEO_HANTRO_DECODER_MEM) += hx170dec_mem.o
obj-$(CONFIG_VIDEO_HANTRO_ENCODER_MEM) += hx280enc_mem.o
obj-$(CONFIG_VIDEO_HWCODEC_DRIVERS) += hantro_codec.o

