obj-$(CONFIG_PINCTRL_SP_I143) += sppctl_inf.o
obj-$(CONFIG_PINCTRL_SP_I143) += sppctl_sysfs.o
obj-$(CONFIG_PINCTRL_SP_I143) += sppctl_pinctrl.o
obj-$(CONFIG_PINCTRL_SP_I143) += sp7021_gpio_inf.o
obj-$(CONFIG_PINCTRL_SP_I143) += sp7021_gpio_ops.o
obj-$(CONFIG_PINCTRL_SP_I143) += sp7021_gpio.o
obj-$(CONFIG_PINCTRL_SP_I143) += sppctl.o
