# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Sunplus Pin control drivers.
#
obj-$(CONFIG_PINCTRL_SPPCTL) += sppctl.o sppctl_pinctrl.o sppctl_sysfs.o sppctl_gpio_ops.o sppctl_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL) += pinctrl_inf_sp7021.o gpio_inf_sp7021.o

obj-$(CONFIG_PINCTRL_SPPCTL_Q645) += sppctl.o sppctl_pinctrl.o sppctl_sysfs.o sppctl_gpio_ops.o sppctl_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL_Q645) += pinctrl_inf_q645.o gpio_inf_q645.o

obj-$(CONFIG_PINCTRL_SPPCTL_SP7350) += sppctl.o sppctl_pinctrl.o sppctl_sysfs.o sppctl_gpio_ops.o sppctl_gpio.o
obj-$(CONFIG_PINCTRL_SPPCTL_SP7350) += pinctrl_inf_sp7350.o gpio_inf_sp7350.o
