#
# Makefile for the gpio module drivers.
#

obj-y += gpio_drv.o

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions


#PWD         := $(shell pwd) 
#KVERSION    := $(shell uname -r)
#KERNEL_DIR   = /usr/src/linux-headers-$(KVERSION)/

#MODULE_NAME  = gpio_drv
#obj-m       := $(MODULE_NAME).o   
#INC_DIR = ../mach



#all:
#	make  -I$(INC_DIR) -C $(KERNEL_DIR) M=$(PWD) modules
#clean:
#	make -C $(KERNEL_DIR) M=$(PWD) clean