snd-soc-spaudio628-1-objs := sunplus_audio.o cpu_dai.o spsoc-tdm.o spsoc-pdm.o spsoc_util.o aud_hw.o
snd-soc-codec628-2-objs := aud_codec.o
snd-soc-pcm628-3-objs := spsoc_pcm.o
snd-soc-aud628-4-objs := spsoc_aud.o

obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-spaudio628-1.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-codec628-2.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-pcm628-3.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-aud628-4.o

