snd-soc-spaudio628-1-objs := sunplus_audio.o cpu_dai.o spsoc-tdm.o spsoc-pdm.o spsoc_util.o aud_hw.o
snd-soc-codec628-2-objs := aud_codec.o
snd-soc-pcm628-3-objs := spsoc_pcm.o
snd-soc-aud628-4-objs := spsoc_aud.o

obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-spaudio628-1.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-codec628-2.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-pcm628-3.o
obj-$(CONFIG_SND_SOC_AUD628)	+= snd-soc-aud628-4.o

snd-soc-spaudio645-1-objs := sunplus_audio.o cpu_dai-645.o spsoc_tdm-645.o spsoc_util.o aud_hw.o
snd-soc-codec645-2-objs := aud_codec-645.o
snd-soc-pcm645-3-objs := spsoc_pcm-645.o
snd-soc-aud645-4-objs := spsoc_aud-645.o

obj-$(CONFIG_SND_SOC_AUD645)	+= snd-soc-spaudio645-1.o
obj-$(CONFIG_SND_SOC_AUD645)	+= snd-soc-codec645-2.o
obj-$(CONFIG_SND_SOC_AUD645)	+= snd-soc-pcm645-3.o
obj-$(CONFIG_SND_SOC_AUD645)	+= snd-soc-aud645-4.o
