/*
 * SC7021 pinmux controller driver.
 * Copyright (C) SunPlus Tech/Tibbo Tech. 2019
 * Author: Dvorkin Dmitry <dvorkin@tibbo.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "sppctl.h"

const char * const list_funcs[] = {
 "GPIO",
 "L2SW_CLK_OUT",
 "L2SW_MAC_SMI_MDC",
 "L2SW_LED_FLASH0",
 "L2SW_LED_FLASH1",
 "L2SW_LED_ON0",
 "L2SW_LED_ON1",
 "L2SW_MAC_SMI_MDIO",
 "L2SW_P0_MAC_RMII_TXEN",
 "L2SW_P0_MAC_RMII_TXD0",
 "L2SW_P0_MAC_RMII_TXD1",
 "L2SW_P0_MAC_RMII_CRSDV",
 "L2SW_P0_MAC_RMII_RXD0",
 "L2SW_P0_MAC_RMII_RXD1",
 "L2SW_P0_MAC_RMII_RXER",
 "L2SW_P1_MAC_RMII_TXEN",
 "L2SW_P1_MAC_RMII_TXD0",
 "L2SW_P1_MAC_RMII_TXD1",
 "L2SW_P1_MAC_RMII_CRSDV",
 "L2SW_P1_MAC_RMII_RXD0",
 "L2SW_P1_MAC_RMII_RXD1",
 "L2SW_P1_MAC_RMII_RXER",
 "DAISY_MODE",
 "SDIO_CLK",
 "SDIO_CMD",
 "SDIO_D0",
 "SDIO_D1",
 "SDIO_D2",
 "SDIO_D3",
 "PWM0",
 "PWM1",
 "PWM2",
 "PWM3",
 "PWM4",
 "PWM5",
 "PWM6",
 "PWM7",
 "ICM0_D",
 "ICM1_D",
 "ICM2_D",
 "ICM3_D",
 "ICM0_CLK",
 "ICM1_CLK",
 "ICM2_CLK",
 "ICM3_CLK",
 "SPIM0_INT",
 "SPIM0_CLK",
 "SPIM0_EN",
 "SPIM0_DO",
 "SPIM0_DI",
 "SPIM1_INT",
 "SPIM1_CLK",
 "SPIM1_CEN",
 "SPIM1_DO",
 "SPIM1_DI",
 "SPIM2_INT",
 "SPIM2_CLK",
 "SPIM2_CEN",
 "SPIM2_DO",
 "SPIM2_DI",
 "SPIM3_INT",
 "SPIM3_CLK",
 "SPIM3_CEN",
 "SPIM3_DO",
 "SPIM3_DI",
 "SPI0S_INT",
 "SPI0S_CLK",
 "SPI0S_EN",
 "SPI0S_DO",
 "SPI0S_DI",
 "SPI1S_INT",
 "SPI1S_CLK",
 "SPI1S_EN",
 "SPI1S_DO",
 "SPI1S_DI",
 "SPI2S_INT",
 "SPI2S_CLK",
 "SPI2S_EN",
 "SPI2S_DO",
 "SPI2S_DI",
 "SPI3S_INT",
 "SPI3S_CLK",
 "SPI3S_EN",
 "SPI3S_DO",
 "SPI3S_DI",
 "I2CM0_CK",
 "I2CM0_DAT",
 "I2CM1_CK",
 "I2CM1_DAT",
 "I2CM2_CK",
 "I2CM2_D",
 "I2CM3_CK",
 "I2CM3_D",
 "UA1_TX",
 "UA1_RX",
 "UA1_CTS",
 "UA1_RTS",
 "UA2_TX",
 "UA2_RX",
 "UA2_CTS",
 "UA2_RTS",
 "UA3_TX",
 "UA3_RX",
 "UA3_CTS",
 "UA3_RTS",
 "UA4_TX",
 "UA4_RX",
 "UA4_CTS",
 "UA4_RTS",
 "TIMER0_INT",
 "TIMER1_INT",
 "TIMER2_INT",
 "TIMER3_INT",
 "GPIO_INT0",
 "GPIO_INT1",
 "GPIO_INT2",
 "GPIO_INT3",
 "GPIO_INT4",
 "GPIO_INT5",
 "GPIO_INT6",
 "GPIO_INT7",
 NULL
};

const size_t sizeof_listF = sizeof( list_funcs)/sizeof( *( list_funcs));
